### ISSUE TITLE
About the comparation results with OmniControl

### ISSUE THREAD

**Issue by CDLCHOI** [HiWilliamWWL/TLControl#1]
Hello, OmniControl's code release data is Dec 10, but the inference visualization results of OmniControl are attached in your paper (Nov 30 on arxiv) . 
I am confused that ，did you implement OmniControl by yourself and get the result?

**Comment by HiWilliamWWL** [comment]
Hi, I know the authors of OmniControl, so I directly approached them for help. I am very grateful for the generous assistance provided which enabled us to achieve the corresponding results.

**Comment by HiWilliamWWL** [comment]
Hi, I know the authors of OmniControl, so I directly approached them for help. I am very grateful for the generous assistance provided which enabled us to achieve the corresponding results.

**Comment by CDLCHOI** [comment]
Oh, got it. Thanks for your reply
